[package]
name = "runtime"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A runtime library for multi-thread applications"

[lib]
path = "src/runtime.rs"

[dependencies]
