name: Pre-commit Checks

on:
  push: {}
  workflow_dispatch: {}

env:
  GERRIT_URL: https://gerrithub.io

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout full history so hooks can see all files
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2) Cache pre-commit environments for speed
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-

      # 3) Set up Python for pre-commit
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 4) Install pre-commit
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      # 5) Run all pre-commit hooks against the repo
      - name: Run pre-commit
        id: tidy
        run: pre-commit run --all-files --show-diff-on-failure

      # 6) If this was a Gerrit push (refs/changes/…), extract its Change-ID
      - name: Determine Gerrit Change ID
        if: >
          github.event_name == 'push' &&
          startsWith(github.ref, 'refs/changes/')
        run: |
           REF="${GITHUB_REF}"
           CHANGE_ID=$(echo "$REF" | sed -E 's,refs/changes/([0-9]+)/.*,\1,')
           echo "CHANGE_ID=$CHANGE_ID" >> $GITHUB_ENV

      - name: Post Verified +1 to Gerrit
        if: >
          steps.tidy.outcome == 'success' &&
          github.event_name == 'push' &&
          env.CHANGE_ID
        run: |
          curl -u "${{ secrets.GERRIT_USER }}:${{ secrets.GERRIT_PASSWORD }}" \
               -H "Content-Type: application/json" \
               -X POST \
               -d '{"message":"Pre-commit checks passed","labels":{"Verified":1}}' \
               "${{ env.GERRIT_URL }}/a/changes/${{ env.CHANGE_ID }}/revisions/current/review"
