name: Cleanup Change Branches

on:
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 50  # Adjust based on how many commits to scan

      - name: Get commits
        id: get_commits
        run: |
          git log origin/main..HEAD --pretty=format:"%H" > commits.txt
          echo "COMMITS=$(cat commits.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Find and delete change branches
        run: |
          for commit in ${{ steps.get_commits.outputs.COMMITS }}; do
            change_id=$(git show -s --format='%B' $commit | grep 'Change-Id:' | awk '{print $2}')
            if [ ! -z "$change_id" ]; then
              branch="changes/${change_id}"
#              echo "Deleting branch $branch..."
#              git push origin --delete "$branch" || echo "Branch $branch not found or already deleted"
              git switch $branch
              git pull origin main --rebase
            fi
          done
